dtbo-y += \
	fanspeed-full.dtbo \
	hktft35.dtbo \
	spi0.dtbo \
	pwm_cd.dtbo \
	pwm_ef.dtbo \
	pwmfan-lowtemp.dtbo \
	uart0.dtbo \
	uart1.dtbo \
	sx865x-i2c1.dtbo \
	w1-gpio_p15.dtbo \
	w1-gpio_p22.dtbo

targets += $(dtbo-y)
always-y := $(dtbo-y)
