#define SGX_FEATURE_MP_CORE_COUNT 1
#define LINUX 
#define PVR_BUILD_DIR "mt6589"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 544
#define SGX544 
#define SUPPORT_SGX544 
#define SUPPORT_SGX 
#define SGX_CORE_REV 115
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define SUPPORT_LISR_MISR_SYNC 
#define DISPLAY_CONTROLLER mtklfb
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 5400
#define PVR_LINUX_MEM_AREA_USE_VMAP 
#define PVR_LINUX_MEM_AREA_POOL_ALLOW_SHRINK 
#define RELEASE 
#define DEBUG_LINUX_MEMORY_ALLOCATIONS 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_FEATURE_SYSTEM_CACHE 
#define SGX_FEATURE_MP 
#define PVRSRV_USSE_EDM_STATUS_DEBUG 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define PVRSRV_NEED_PVR_DPF 
#define SUPPORT_ION 
#define SUPPORT_PVRSRV_DEVICE_CLASS 
#define IMG_ADDRSPACE_PHYSADDR_BITS 32
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define PVRSRV_DUMP_MK_TRACE 
#define SUPPORT_LARGE_GENERAL_HEAP 
#define TTRACE 
#define ANDROID 
#define SUPPORT_PVRSRV_ANDROID_SYSTRACE 
#define PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC 
#define SUPPORT_ION_HEADER "linux/ion.h"
#define SUPPORT_ION_PRIV_HEADER "../drivers/gpu/ion/ion_priv.h"
#define USE_RGBA_8888_FB 
#define MTK_DEBUG_LFB 
#define MTK_DEBUG_TIMER_MONITOR 
#define MTK_DEBUG_MSG_LENGTH 512
#define MTK_DEBUG_PROC_PRINT 
#define MTK_DEBUG 
#define MTK_HAL_MM_STATISTIC 
#define MTK_FREQ_OD_INIT 
