# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_JZ4730_ALPHA400)	+= alpha400.dtb
dtb-$(CONFIG_JZ4740_QI_LB60)	+= qi_lb60.dtb
dtb-$(CONFIG_JZ4740_RS90)	+= rs90.dtb
dtb-$(CONFIG_JZ4770_GCW0)	+= gcw0.dtb
dtb-$(CONFIG_JZ4780_CI20)	+= ci20.dtb
dtb-$(CONFIG_X1000_CU1000_NEO)	+= cu1000-neo.dtb
dtb-$(CONFIG_X1600_LX16)	+= lx16.dtb
dtb-$(CONFIG_X1830_CU1830_NEO)	+= cu1830-neo.dtb
dtb-$(CONFIG_X2000_LX20)	+= lx20.dtb

dtb-$(CONFIG_INGENIC_GENERIC_BOARD)	+= alpha400.dtb \
					   qi_lb60.dtb \
					   rs90.dtb \
					   gcw0.dtb \
					   ci20.dtb \
					   cu1000-neo.dtb \
					   lx16.dtb \
					   cu1830-neo.dtb

dtb-$(CONFIG_INGENIC_GENERIC_BOARD)	+= alpha400.dtb \
					   qi_lb60.dtb \
					   rs90.dtb \
					   gcw0.dtb \
					   ci20.dtb \
					   cu1000-neo.dtb \
					   cu1830-neo.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
