#ifndef _DT_BINDINGS_POWER_H
#define _DT_BINDINGS_POWER_H

#define POWER_SUPPLY_TECHNOLOGY_NiMH 1
#define POWER_SUPPLY_TECHNOLOGY_LION 2
#define POWER_SUPPLY_TECHNOLOGY_LIPO 3
#define POWER_SUPPLY_TECHNOLOGY_LiFe 4
#define POWER_SUPPLY_TECHNOLOGY_NiCd 5
#define POWER_SUPPLY_TECHNOLOGY_LiMn 6

#endif /* _DT_BINDINGS_POWER_H */
