snd-soc-omap-aess-objs := omap-aess-core.o \
			omap-aess-dbg.o \
			omap-aess-fw.o \
			omap-aess-pcm.o \
			omap-aess-dai.o \
			aess_opp.o \
			aess_asrc.o \
			aess_utils.o \
			aess_ini.o \
			aess_gain.o \
			aess_port.o \
			port_mgr.o \

obj-$(CONFIG_SND_OMAP_SOC_AESS) += snd-soc-omap-aess.o
