#define SGX_FEATURE_MP_CORE_COUNT 1
#define LINUX
#define PVR_BUILD_DIR "sunxi_linux"

#ifdef CONFIG_IMG_SGX_5xx_BUILD_DEBUG
#define PVR_BUILD_TYPE "debug"
#else
#define PVR_BUILD_TYPE "release"
#endif

#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 544
#define SGX544
#define SUPPORT_SGX544
#define SUPPORT_SGX
#define SGX_CORE_REV 115
#define TRANSFER_QUEUE
#define PVR_SECURE_HANDLES
#define SUPPORT_LISR_MISR_SYNC
#define DISPLAY_CONTROLLER dc_sunxi
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 0
#define RELEASE
#define SUPPORT_PERCONTEXT_PB
#define SUPPORT_HW_RECOVERY
#define SUPPORT_SGX_HWPERF
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING
#define SUPPORT_SGX_NEW_STATUS_VALS
#define SUPPORT_PDUMP_MULTI_PROCESS
#define SUPPORT_DBGDRV_EVENT_OBJECTS
#define SGX_FEATURE_SYSTEM_CACHE
#define SGX_FEATURE_MP
#define PDUMP
#define SYS_USING_INTERRUPTS
#define SUPPORT_PVRSRV_DEVICE_CLASS
#define SUPPORT_PVRSRV_GET_DC_SYSTEM_BUFFER
#define IMG_ADDRSPACE_PHYSADDR_BITS 32
#define SUPPORT_LINUX_X86_WRITECOMBINE
#define SUPPORT_LINUX_X86_PAT
#define SYS_CUSTOM_POWERLOCK_WRAP
#define PVR_LINUX_USING_WORKQUEUES
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE
#define PVR_LINUX_TIMERS_USING_WORKQUEUES
#define LDM_PLATFORM
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define XPROC_WORKAROUND_NUM_SHAREABLES 4095
#define SUPPORT_DRI_DRM
#define PVR_SECURE_DRM_AUTH_EXPORT
#define PVR_DISPLAY_CONTROLLER_DRM_IOCTL
#define PVR_DRI_DRM_PLATFORM_DEV
#define DC_NOHW_BUFFER_WIDTH
#define DC_NOHW_BUFFER_HEIGHT

#ifdef CONFIG_IMG_SGX_5xx_DEBUG
#define PVRSRV_USSE_EDM_STATUS_DEBUG
#define PVRSRV_NEED_PVR_DPF
#define PVRSRV_DUMP_MK_TRACE
#endif

#ifdef CONFIG_IMG_SGX_5xx_BUILD_DEBUG
#define DEBUG
#define DEBUG_LINUX_MEMORY_ALLOCATIONS
#define DEBUG_LINUX_MEM_AREAS
#define DEBUG_LINUX_MMAP_AREAS
#define DEBUG_BRIDGE_KM
#endif
