#define SGX_FEATURE_MP_CORE_COUNT 1
#define LINUX 
#define PVR_BUILD_DIR "omap_linux"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 544
#define SGX544 
#define SUPPORT_SGX544 
#define SUPPORT_SGX 
#define SGX_CORE_REV 115
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define SUPPORT_LISR_MISR_SYNC 
#define DISPLAY_CONTROLLER omaplfb
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 0
#define RELEASE 
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_FEATURE_SYSTEM_CACHE 
#define SGX_FEATURE_MP 
#define SYS_USING_INTERRUPTS 
#define SUPPORT_PVRSRV_DEVICE_CLASS 
#define SUPPORT_PVRSRV_GET_DC_SYSTEM_BUFFER 
#define IMG_ADDRSPACE_PHYSADDR_BITS 32
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_PLATFORM_PRE_REGISTERED 
#define PVR_LDM_PLATFORM_PRE_REGISTERED_DEV "pvrsrvkm"
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define SUPPORT_OLD_ION_API 
#define XPROC_WORKAROUND_NUM_SHAREABLES 4095
#define SUPPORT_DRI_DRM 
#define PVR_SECURE_DRM_AUTH_EXPORT 
#define PVR_DISPLAY_CONTROLLER_DRM_IOCTL 
#define PVR_DRI_DRM_PLATFORM_DEV 
#define PVR_OMAPLFB_DONT_USE_FB_PAN_DISPLAY 
