# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Ingenic JZ4740.
#

# Object file lists.
CFLAGS_setup.o = -I$(src)/../../../scripts/dtc/libfdt

# SMP support
obj-$(CONFIG_SMP) += smp.o
obj-$(CONFIG_SMP) += smp-entry.o
