dtbo-y += \
	hktft32.dtbo \
	hktft35.dtbo \
	pcf8563.dtbo \
	spi0.dtbo \
	sx865x-i2c1.dtbo \
	uart0.dtbo \
	uart1.dtbo \
	uart2.dtbo \
	uart3.dtbo \
	w1-gpio_p15.dtbo \
	w1-gpio_p22.dtbo \
	hifishield2.dtbo

targets += $(dtbo-y)
always-y := $(dtbo-y)
