#!/bin/bash
#
# Author: H. Nikolaus Schaller <hns@goldelico.com>
#
# adjust screen size and touch depending on device model
#

# NOTE: basically we need to map the panel model (and not a board name) to a config
# but there is no canonical way to find out the panel model name
# /sys/class/lcd may be empty and panels don't have a 'model' attribute.
# But they have a compatible attribute!
# So we have to locate the panel at some well known locations (processor dependent)
# and get the comptatible record
# Then we can look for $COMPATIBLE.conf
# And finally apply some special rules (e.g. run daemons) through a shell script
# Well, in practice we have to see how to handle the mix with touch screens and different
# panel mount orientation which we do NOT know through the panel compatible string

findpanel() { # search panel compatible string at some well known locations

# use something like
#   find /proc/device-tree/ -name compatible -exec fgrep td028 {} \; -print
# to define the search locations

for LCD in \
	/proc/device-tree/lcd \
	/proc/device-tree/panel/display-timings \
	/proc/device-tree/spi_lcd/td028ttec1@0 \
	/proc/device-tree/ocp@68000000/spi@48098000/lcd@1 \
	/proc/device-tree/ocp/dss@58000000/encoder@58004000/lcd
do
# echo $0: try $LCD/compatible >&2
	if [ -r $LCD/compatible ]
	then
		tr '\0' '\n' <$LCD/compatible 2>/dev/null | sed s/omapdss,//
		return
	fi
done
}

while read COMPATIBLE < <(findpanel)
do
# echo check "/etc/X11/$COMPATIBLE.conf" >&2
	if [ -r "/etc/X11/$COMPATIBLE.conf" ]
	then
		# create symlink to chosen config
echo $0: ln -s $COMPATIBLE.conf /etc/X11/xorg.conf >&2
		rm -f /etc/X11/xorg.conf
		ln -s "$COMPATIBLE.conf" /etc/X11/xorg.conf
		# look for and run shell script $COMPATIBLE.sh if it exists
		[ -x "/etc/X11/$COMPATIBLE.sh" ] && "/etc/X11/$COMPATIBLE.sh"
		exit 0
	fi
done

function model_or_compatible {
	if [ -r /proc/device-tree/model ]
	then
		tr -d '\0' </proc/device-tree/model 2>/dev/null
	else	# prefix and separate with @
		echo @$(tr '\0' '@' </proc/device-tree/compatible 2>/dev/null)
		
	fi
}

case "$(model_or_compatible)" in
	*'GTA04 b4'* )
		PANEL=5.0x640x1024;;	# Letux 5004 (never built)
	*GTA04b7* | \
	*'GTA04 b7'* | \
	*Neo900* )
		PANEL=3.0-800x480;;	# Neo900
	*'GTA04 b8'* )
		PANEL=2.0-320x320;;	# Letux 2204 (never built)
	*PandaBoard* | \
	*OMAP5*uEVM* | \
	*PinePhone* )
		PANEL=none;;
	*LC15-EVM* )
		PANEL=5.0-720x1280
		/root/tvout 0   # seems to initialize something we need for switching to HDMI
		/root/tvout 1   # choose HDMI video as default
		;;
	*Pandora* )
		PANEL=4.3-480x640
		# setup keyboard
		# cp /etc/X11/Xmodmap.pandora /etc/X11/Xmodmap
		# setup nubs
		echo mouse > /proc/pandora/nub0/mode	# mouse
		echo mbuttons > /proc/pandora/nub1/mode	# mouse buttons
		;;
	*'Letux Cortex 8'* )
		PANEL=4.3-272x480;;	# assume a PSP display can be connected
	*'Raspberry Pi'* )
		PANEL=raspi;;
	*'UDOO Neo'* )
		PANEL=udoo;;
	*@img,ci20@* )
		PANEL=ci20;;
	*@letux400,minipc@* )
		PANEL=7.0-640x480;;
	* )
		echo "$0: unknown motherboard $(model_or_compatible)"
		PANEL=none
		;;
esac

# symlink to chosen config (if any)
rm -f /etc/X11/xorg.conf
if [ -r "$PANEL.conf" ]
then ln -s $PANEL.conf /etc/X11/xorg.conf
fi
