#!/bin/bash
#
# Author: H. Nikolaus Schaller <hns@goldelico.com>
#
# adjust screen size and touch depending on device model
#

# NOTE: basically we need to map the panel model (and not a board name) to a config
# but there is no canonical way to find out the panel model name
# /sys/class/lcd may be empty and panels don't have a 'model' attribute.
# But they have a compatible attribute!
# So we have to locate the panel at some well known locations (processor dependent)
# and get the comptatible record
# Then we can look for $COMPATIBLE.conf
# And finally apply some special rules (e.g. run daemons) through a shell script
# Well, in practice we have to see how to handle the mix with touch screens and different
# panel mount orientation which we do NOT know through the panel compatible string

findpanel() { # search panel compatible string at some well known locations

# use something like
#   find /proc/device-tree/ -name compatible -exec fgrep td028 {} \; -print
# to define the search locations

for LCD in \
	/proc/device-tree/lcd \
	/proc/device-tree/panel/display-timings \
	/proc/device-tree/spi_lcd/td028ttec1@0 \
	/proc/device-tree/ocp@68000000/spi@48098000/lcd@1 \
	/proc/device-tree/ocp/dss@58000000/encoder@58004000/lcd
do
echo try $LCD/compatible >&2
	if [ -r $LCD/compatible ]
	then
		tr '\0' '\n' <$LCD/compatible 2>/dev/null | sed s/omapdss,//
		return
	fi
done
}

findpanel | while read COMPATIBLE
do
echo check "/etc/X11/$COMPATIBLE.conf" >&2
	if [ -r "/etc/X11/$COMPATIBLE.conf" ]
	then
		# create symlink to chosen config
echo ln -s $COMPATIBLE.conf /etc/X11/xorg.conf >&2
		rm -f /etc/X11/xorg.conf
		ln -s "$COMPATIBLE.conf" /etc/X11/xorg.conf
		# apply special rules, could look for and run shell script $COMPATIBLE.sh

		[ -x "/etc/X11/$COMPATIBLE.sh" ] && "/etc/X11/$COMPATIBLE.sh"
		exit 0
	fi
done


case "$(tr -d '\0' </proc/device-tree/model 2>/dev/null)" in
#	*GTA04A2* | *GTA04A3* | *GTA04A4* | *GTA04A5* | *GTA04A3+* | *Letux2804* )
#		PANEL=2.8-640x480;;	# Letux 2804
#	*'GTA04 b1'* | *OpenMoko-Beagle-Hybrid* )
#		PANEL=2.8-640x480;;	# OpenmokoBeagleHybrid (with TPO LCD conneced to J4&5)
#	*GTA04b2* | *'GTA04 b2'* | *GTA04b6* | *'GTA04 b6'* | *'Letux 3704'* | *'Letux 3714'* )
#		(
#		cd /root
#		NAME=blanviewd
#		[ -x $NAME ] || make $NAME
#		daemon --name=$NAME $PWD/$NAME
#		)
#		PANEL=3.7-640x480;;	# Letux 3704
#	*GTA04b3* | *'GTA04 b3'* | *'Letux 7004'* )
#		PANEL=7.0-480x800;;	# Letux 7004
	*'GTA04 b4'* )
		PANEL=5.0x640x1024;;	# Letux 5004 (never built)
	*GTA04b7* | *'GTA04 b7'* | *Neo900* )
		PANEL=3.0-800x480;;	# Neo900
	*'GTA04 b8'* )
		PANEL=2.0-320x320;;	# Letux 2204 (never built)
	*PandaBoard* |	*OMAP5*uEVM* )
		PANEL=none;;
	*LC15-EVM* )
		PANEL=5.0-720x1280
		/root/tvout 0   # seems to initialize something we need for switching to HDMI
		/root/tvout 1   # choose HDMI video as default
		;;
#	*Pyra-Handheld* )
#		PANEL=5.0-720x1280
#		(
#		cd /root
#		if [ "$(tr -d '\0' </proc/device-tree/ocp/dss@58000000/encoder@58004000/lcd/compatible)" = "omapdss,mipi,debug" ]
#		then
#			PANEL=5.0-720x1280-debug
#			if [ -r /sys/bus/i2c/devices/1-0048 ]
#			then	# old V3 touch&display adapter for display demo/tester
#				./boe-w677l
#			else
#				./ssd2858 -r -p -s	# start ssd
#			fi
#			./bl 1
#		else
#			# assume we have a native and working panel driver and need to rotate by tiler
#			./tiler-ctl 270
#		fi
#		)
#		# setup keyboard
#		cp /etc/X11/Xmodmap.pyra /etc/X11/Xmodmap
#		# setup nubs
#		echo mouse > /proc/pandora/nub0/mode	# mouse
#		echo scroll > /proc/pandora/nub1/mode	# scroll wheel
#		# mouse buttons are handled by gpio-buttons
#		;;
	*Pandora* )
		PANEL=4.3-480x640
		# setup keyboard
		# cp /etc/X11/Xmodmap.pandora /etc/X11/Xmodmap
		# setup nubs
		echo mouse > /proc/pandora/nub0/mode	# mouse
		echo mbuttons > /proc/pandora/nub1/mode	# mouse buttons
		;;
	*BeagleBoneBlack* )
		PANEL=4.3-272x480;;	# BBB with 4.3 inch panel cape
	*'Letux Cortex 8'* )
		PANEL=4.3-272x480;;	# assume a PSP display can be connected
	*'Raspberry Pi'* )
		PANEL=raspi;;
	*'UDOO Neo'* )
		PANEL=udoo;;
	* )
		echo "unknown motherboard $(tr -d '\0' </proc/device-tree/model 2>/dev/null)"
		echo "we don't know how to configure X11 for the display"
		exit 1
		;;
esac

# symlink to chosen config
rm -f /etc/X11/xorg.conf
ln -s $PANEL.conf /etc/X11/xorg.conf
