#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. /etc/X11/Xsession

# this is NOT loaded because the script does an exit!
# so this is the wrong approach

# load Pyra keyboard definitions
[ -r /root/Xmodmap ] && xmodmap /etc/X11/Xmodmap
