#!/bin/bash

[ "$(which sysbench)" ] || yes | apt-get install -y sysbench

PROCESSORS=$(nproc --all)

uname -a
echo sysbench --num-threads=$PROCESSORS --test=cpu --cpu-max-prime=1000 run
sysbench --num-threads=$PROCESSORS --test=cpu --cpu-max-prime=1000 run
