#!/bin/bash
mount | fgrep -q debugfs || mount -t debugfs none /sys/kernel/debug

case "$1" in
	dsi )
		cat /sys/kernel/debug/omapdss/clk
		cat /sys/kernel/debug/omapdss/dispc
		cat /sys/kernel/debug/omapdss/dsi1_irqs
		cat /sys/kernel/debug/omapdss/dsi1_regs
		;;
	mmc )
		for i in /sys/kernel/debug/mmc*
		do
			echo "$(basename "$i"):"
			cat $i/ios
			cat $i/regs
		done
		;;
esac
