#!/bin/bash
# find iio device by name

LIST=false
if [ "$1" = "-a" ]
then
	LIST=true
	shift
fi

for dev in /sys/bus/iio/devices/iio:device*
do
	$LIST && cat $dev/name
	if [ "$(cat $dev/name 2>/dev/null)" = "$1" ]
		then echo $dev
		exit 0
	fi
done
$LIST || exit 1