#!/bin/bash
#
# start fm demo
#
# fm-demo freq-in-MHz
#

SCRIPTPATH="$(dirname "$0")"
make si4721

# turn off after exit of this script
trap "$SCRIPTPATH/si4721 -r 0 -dn; killall arecord" EXIT
trap "exit 1" INT TERM QUIT HUP

NUM=$($SCRIPTPATH/findsoundcard "gta04")

echo 1 >/sys/devices/virtual/gpio/gpio55/value  # enable audio out
amixer -c "$NUM" set 'Headset' 2
amixer -c "$NUM" set 'HeadsetL Mixer AudioL1' off
amixer -c "$NUM" set 'HeadsetL Mixer AudioL2' on
amixer -c "$NUM" set 'HeadsetL Mixer Voice' off
amixer -c "$NUM" set 'HeadsetR Mixer AudioR1' off
amixer -c "$NUM" set 'HeadsetR Mixer AudioR2' on
amixer -c "$NUM" set 'HeadsetR Mixer Voice' off

FREQ=$1; [ "$1" ] || FREQ=92.4

# power on (and print chip ID)
$SCRIPTPATH/si4721 -d -up
# tune to specified frequency
echo $SCRIPTPATH/si4721 -t $(python -c "print '%.0f' % ($FREQ*100)")
$SCRIPTPATH/si4721 -t $(python -c "print '%.0f' % ($FREQ*100)")
sleep 1
$SCRIPTPATH/si4721 -ts
# start PCM (incl. clocks)
arecord -Ddefault:CARD=Tuner -c2 -fS16_LE -r48000 | tee radio.wav | aplay&	# receiver -> earpiece / speaker / headset
# arecord -fS16_LE -c2 -r48000 | aplay -Dhw:4,0 &	# microphone -> transmitter
# set sample rate (32 .. 48 kHz)
$SCRIPTPATH/si4721 -r 48000
# loop and print signal strength
while true
## FIXME: loop should abort when arecord aborts (PCM error)
do
	# print signal strength
	$SCRIPTPATH/si4721 -s
	sleep 1
done
