#!/bin/bash

BUS="$1"
[ "$BUS" ] || BUS=0

function cmd {
	echo $@ >&2
	$@
}

# read 1 byte
cmd i2cget -f -y $BUS 0x28
# write 1 + read 1
cmd i2cget -f -y $BUS 0x28 0
# write 1 + read 2
cmd i2cget -f -y $BUS 0x28 0 w
# read 2 (no responder)
cmd i2cget -f -y $BUS 0x29 0 w
# write 1
cmd i2cset -f -y $BUS 0x13 0
# write 2
cmd i2cset -f -y $BUS 0x13 0 0x00
# read 1 at each address
cmd i2cdetect -y -r $BUS 0x27 0x29 >/tmp/$$ && cat /tmp/$$
# write 0 bytes at each address
cmd i2cdetect -y $BUS 0x27 0x29 >/tmp/$$ && cat /tmp/$$