#!/bin/bash

PATH=.:$PATH:/usr/bin/$(echo $MACHTYPE | sed s/unknown-//g)

BASE=10020000

function lcdcregisters {

cat <<END
/* jz4730 */

#define JZ_REG_AIC_CONF		0x00
#define JZ_REG_AIC_CTRL		0x04
#define JZ_REG_AIC_I2S_FMT		0x10
#define JZ_REG_AIC_FIFO_STATUS		0x14
#define JZ_REG_AIC_I2S_STATUS		0x1c
#define JZ_REG_AIC_CLK_DIV		0x30
#define JZ_REG_AIC_FIFO		0x34

END
}

lcdcregisters | while read DEFINE REGISTER OFFSET
do
	case "$DEFINE" in
	'#define' )
		ADDR=
		ADDR=$(printf "0x%x" $((0x$BASE + $OFFSET)))
		VAL=$(devmem2 $ADDR w | fgrep 'Value at address' | cut -d ' ' -f 6)
		VAL=$(printf %08x $[$VAL])
		echo $ADDR $VAL $REGISTER
		;;
	esac
done
