#!/bin/sh

# by Neil Brown

# disable charging, suspend for 5 minutes and report apparent
# power usage by monitoring battery.

power1=/sys/class/power_supply/twl4030_usb/mode
power2=/sys/class/power_supply/twl4030_ac/mode
chg=/sys/class/power_supply/bq27000-battery/charge_now
rs232=/sys/class/gpio/gpio13/value
rs232dir=/sys/class/gpio/gpio13/direction
delay=${1-300}
[ -f $rs232 ] || { echo 13 > /sys/class/gpio/export; echo high > $rs232dir;}

stty raw -echo -cread
echo 0 > $rs232
echo off > $power1
echo off > $power2
before=`cat $chg`
start=`date '+%s'`
echo $[start+delay] > /sys/class/rtc/rtc0/wakealarm
echo mem > /sys/power/state
after=`cat $chg`
end=`date '+%s'`
echo 1 > $rs232
stty sane
echo auto > $power1
echo auto > $power2

echo $((before-after)*3600/(end-start)) uA over $((end-start)) seconds