#!/bin/bash

# by Neil Brown

# disable charging, suspend for 5 minutes and report apparent
# power usage by monitoring battery.

case $(cat /proc/device-tree/model 2>/dev/null) in
	*GTA04* )
		power1=/sys/class/power_supply/twl4030_usb/mode
		power2=/sys/class/power_supply/twl4030_ac/mode
		chg=/sys/class/power_supply/bq27000-battery/charge_now
		alarm=/sys/class/rtc/rtc0/wakealarm
		rs232=/sys/class/gpio/gpio13/value
		rs232dir=/sys/class/gpio/gpio13/direction
		[ -f $rs232 ] || { echo 13 > /sys/class/gpio/export; echo high > $rs232dir;}
		[ -r /dev/ttyHS_Application ] && MODEM="with modem on"
		;;
	*Pandora* )
		power1=/sys/class/power_supply/twl4030_usb/mode
		power2=/sys/class/power_supply/twl4030_ac/mode
		chg=/sys/class/power_supply/bq27500-0/charge_now
		alarm=/sys/class/rtc/rtc0/wakealarm
		;;
	*Pyra-Handheld* )
		# FIXME: disabling charging must be done differently
	# FIXME: there is no "mode": power1=/sys/class/power_supply/bq24297/mode
		power3=/sys/class/power_supply/bq24297/input_current_limit
		chg=/sys/class/power_supply/bq27421-0/charge_now
		alarm=/sys/class/rtc/rtc0/wakealarm
		[ -r /dev/ttyACM1 ] && MODEM="with modem on"
		;;
	* )
		echo "unknown device $(cat /proc/device-tree/model 2>/dev/null)"
		exit 1
		;;
esac

delay=${1-300}

echo suspending for $delay seconds >&2
stty raw -echo -cread
# stop RS232
[ "$rs232" ] && echo 0 > $rs232
# turn off external power supplies
[ "$power1" ] && echo off > $power1
[ "$power2" ] && echo off > $power2
[ "$power3" ] && echo 0 > $power3
# turn off LEDs
( cd /sys/class/leds; for i in *; do echo "none" >$i/trigger; done )
before=`cat $chg`
start=`date '+%s'`
echo $[start+delay] > $alarm
echo mem > /sys/power/state
end=`date '+%s'`
after=`cat $chg`
sleep 1
[ "$rs232" ] && echo 1 > $rs232
stty sane
echo did wake up >&2
echo before: $before
echo after: $after
[ "$power1" ] && echo auto > $power1
[ "$power2" ] && echo auto > $power2
[ "$power3" ] && echo 2000000 > $power3

echo average $[(before-after)*3600/(end-start)] uA over $[end-start] seconds $MODEM
