#!/bin/bash
#
# twl: demo and player sound without significant ALSA or PulseAudio setup
#

SCRIPTPATH="$(dirname "$0")"
trap "exit 1" SIGHUP SIGINT SIGTERM

[ -x /usr/bin/sox ] || apt-get install sox libsox-fmt-mp3

MONO=false
HANDSFREE=yes
CARD="$($SCRIPTPATH/findsoundcard -a | head -1)"
DEV=0

while [ "$1" ]
do
        case "$1" in
        "-c" )
		shift
		CARD="$1"
		;;
        "-D" )
		shift
		DEV="$1"
		;;
        "-d" )
		DEMO=yes
		;;
        "-t" )
		shift
		FORMAT="$1";
		;;
        "-lp" )
		LPMODE=yes
		;;
        "-nhf" )
		HANDSFREE=
		;;
	"-m" )
		MONO=true
		;;
	"-" | "-stdin" )
		FILE="-"
		;;
	-* )
		echo unknown option $1
		echo "-c dev	device"
		echo "-d	demo"
		echo "-m	file is mono (1 channel) or take first channel only"
		echo "-lp	low power mode"
		echo "-nhf	keep handsfree off"
		echo "-t fmt	define format"
		echo "-		play data from stdin (use with -t)"
		echo "file...	play files"
		exit 1
		;;
	* )
		break
		;;
	esac
	shift
done

NUM=$($SCRIPTPATH/findsoundcard "$CARD")
if [ ! "$NUM" ]
then
	echo sound card "$CARD" not found >&2
	exit
fi

echo CARD:$CARD DEV:$DEV NUM:$NUM
AUDIOCARD="hw:CARD=$CARD"
AUDIOCARDDEV="hw:CARD=$CARD,DEV=$DEV"
export AUDIODEV="hw:$NUM,$DEV"

# FIXME: make this all depend on presence of amixer controls
# e.g.
# root@letux:~# amixer scontrols
# Simple mixer control 'Master',0
# Simple mixer control 'Headphone',0
# Simple mixer control 'Mic',0
# Simple mixer control 'ADC',0

if [ -r /sys/firmware/devicetree/base/sound/ti,twl6040 ]
then

echo "TWL6040 (Pandaboard, OMAP5432EVM, Pyra, ...)"

amixer -D"$AUDIOCARD" -q set "Aux FM" 0% || exit
amixer -D"$AUDIOCARD" -q set "Capture" 100% || exit
amixer -D"$AUDIOCARD" -q set "Capture Preamplifier" 100% || exit
amixer -D"$AUDIOCARD" -q set "AUXL" "off" || exit
amixer -D"$AUDIOCARD" -q set "AUXR" "off" || exit
amixer -D"$AUDIOCARD" -q set "Analog Left" "Main Mic" || exit
amixer -D"$AUDIOCARD" -q set "Analog Right" "Headset Mic" || exit

# set defaults if we have no volumed
amixer -D"$AUDIOCARD" -q set "Headset" 100% || exit
amixer -D"$AUDIOCARD" -q set "Earphone" 100% || exit
amixer -D"$AUDIOCARD" -q set "Handsfree" 100% || exit

if [ "$HANDSFREE" ] # handsfree on/off
then
	amixer -D"$AUDIOCARD" -q set "Handsfree Left Playback" "HF DAC" || exit
	amixer -D"$AUDIOCARD" -q set "Handsfree Right Playback" "HF DAC" || exit
else
	amixer -D"$AUDIOCARD" -q set "Handsfree Left Playback" "Off" || exit
	amixer -D"$AUDIOCARD" -q set "Handsfree Right Playback" "Off" || exit
fi

amixer -D"$AUDIOCARD" -q set "Headset Left Playback" "HS DAC" || exit
amixer -D"$AUDIOCARD" -q set "Headset Right Playback" "HS DAC" || exit
amixer -D"$AUDIOCARD" -q set "Analog Left" "Main Mic" || exit

if [ "$LPMODE" ] # low power mode
then
	amixer -D"$AUDIOCARD" -q set "Headset Power Mode" "Low-Power" || exit
	amixer -D"$AUDIOCARD" -q set "PLL Selection" "Low-Power" || exit
else
	amixer -D"$AUDIOCARD" -q set "Headset Power Mode" "High-Performance" || exit
	amixer -D"$AUDIOCARD" -q set "PLL Selection" "High-Performance" || exit
fi

amixer -D"$AUDIOCARD" -q set "Vibra Left Playback" "Input FF" || exit
amixer -D"$AUDIOCARD" -q set "Vibra Right Playback" "Input FF" || exit

: amixer -D"$AUDIOCARD" -q set "Vibra Left Playback" "Audio PDM" || exit
: amixer -D"$AUDIOCARD" -q set "Vibra Right Playback" "Audio PDM" || exit

REMIX_MONO="remix 1 1 1 1"
REMIX_STEREO="remix 1 2 1 2"

elif [ -r /sys/firmware/devicetree/base/sound/ti,twl6040 ]
then

echo "TWL4030 (GTA04, ...)"

amixer -D"$AUDIOCARD" -q set "AVADC Clock Priority" "HiFi high priority" || exit
amixer -D"$AUDIOCARD" -q set "DAC1 Analog" off || exit
amixer -D"$AUDIOCARD" -q set "DAC2 Analog" on || exit
amixer -D"$AUDIOCARD" -q set "DAC2 Analog" 5 || exit        # so that total gain is < 1
amixer -D"$AUDIOCARD" -q set "Codec Operation Mode" "Option 2 (voice/audio)" || exit

amixer -D"$AUDIOCARD" -q set "Earpiece" 100% || exit
amixer -D"$AUDIOCARD" -q set "Earpiece Mixer AudioL1" off || exit
amixer -D"$AUDIOCARD" -q set "Earpiece Mixer AudioL2" on || exit
amixer -D"$AUDIOCARD" -q set "Earpiece Mixer AudioR1" off || exit
amixer -D"$AUDIOCARD" -q set "Earpiece Mixer Voice" off || exit

amixer -D"$AUDIOCARD" -q set 'Headset' 2 || exit
amixer -D"$AUDIOCARD" -q set 'HeadsetL Mixer AudioL1' off || exit
amixer -D"$AUDIOCARD" -q set 'HeadsetL Mixer AudioL2' on || exit
amixer -D"$AUDIOCARD" -q set 'HeadsetL Mixer Voice' off || exit
amixer -D"$AUDIOCARD" -q set 'HeadsetR Mixer AudioR1' off || exit
amixer -D"$AUDIOCARD" -q set 'HeadsetR Mixer AudioR2' on || exit
amixer -D"$AUDIOCARD" -q set 'HeadsetR Mixer Voice' off || exit

amixer -D"$AUDIOCARD" -q set "TX1" "Analog" || exit
amixer -D"$AUDIOCARD" -q set "TX1 Digital" 12 || exit

amixer -D"$AUDIOCARD" -q set "Analog Left AUXL" nocap || exit
amixer -D"$AUDIOCARD" -q set "Analog Right AUXR" nocap || exit
amixer -D"$AUDIOCARD" -q set "Analog Left Main Mic" cap || exit
amixer -D"$AUDIOCARD" -q set "Analog Left Headset Mic" nocap || exit

if [ "$NOHANDSFREE" ] # handsfree on/off
then
amixer -D"$AUDIOCARD" -q set HandsfreeL off || exit
amixer -D"$AUDIOCARD" -q set HandsfreeR off || exit
else
amixer -D"$AUDIOCARD" -q set HandsfreeL on || exit
amixer -D"$AUDIOCARD" -q set HandsfreeR on || exit
fi
amixer -D"$AUDIOCARD" -q set "Analog" 5 || exit
amixer -D"$AUDIOCARD" -q set "HandsfreeL Mux" AudioL2 || exit
amixer -D"$AUDIOCARD" -q set "HandsfreeR Mux" AudioR2 || exit

REMIX_MONO=""
REMIX_STEREO=""

elif false
then

echo "CI20 or simplesoundcard"

root@letux:~# amixer -c "0" -q set "Master" 100%
root@letux:~# amixer -c "0" -q set "Headphone" 100%
root@letux:~# amixer -c "0" -q set "Mic" 100%
root@letux:~# amixer -c "0" -q set "ADC" "AIP2"

REMIX_MONO=""
REMIX_STEREO=""

fi

if [ "$DEMO" ] # demo
then
	echo "play default sounds (Front Center etc.)"
	aplay -D"$AUDIOCARDDEV" -q /usr/share/sounds/alsa/*.wav
	echo "play chirp sound on all channels"
	sox -c 4 -n -t wav - synth 10 sine 10-100 | aplay -D"$AUDIOCARDDEV"
	echo "remix for Pandaboard/OMAP5 stereo"
	play /usr/share/sounds/alsa/Front_Center.wav $REMIX_MONO
	if [ "$FILE" ]
	then
		echo play $FILE
		play $FILE
	fi
	exit 0
fi

# play mono/stereo on headset and main speakers
$MONO && REMIX="$REMIX_MONO" || REMIX="$REMIX_STEREO"

if [ "$1" ]
then
	for FILE in "$@"
	do
		play ${FORMAT:+-t} ${FORMAT:+$FORMAT} -v 0.98 $FILE $REMIX
	done
fi
exit 0
