#!/bin/sh
#
# Pyra volume control daemon
#
SCRIPTPATH="$(dirname "$0")"
GPADC=$($SCRIPTPATH/findiio "palmas-gpadc")
NUM=$($SCRIPTPATH/findsoundcard "L15")	# twl6040 on Pyra

if [ ! "GPADC" ]
then
	echo no volume wheel found >&2
	exit
fi
if [ ! "$NUM" ]
then
	echo no sound card found >&2
	exit
fi

LASTVOL="unknown"
MAXWHEEL=1200	# reports 0..1250 mV but leave some margin

while [ "$1" ]
do
        case "$1" in
        "-q" )
		QUIET=true
		;;
        "-nhf" )
		NOHANDSFREE=yes
		;;
	* )
		break
		;;
	esac
	shift
done

while true
do
	WHEEL=$(cat $GPADC/in_voltage2_input 2>/dev/null)
	# could apply non-linear scale for more intuitive control
	VOL=$(( 100 * ${WHEEL:-0} / $MAXWHEEL ))
	[ "$VOL" -lt 0 ] && VOL=0
	[ "$VOL" -gt 100 ] && VOL=100
	# should check for abs($VOL-$LASTVOL) > threshold
	if [ "$VOL" != "$LASTVOL" ]
	then # update only if changed since amixer -c "$NUM" command needs some resources
		[ "$QUIET" ] || echo $WHEEL - $VOL%
		if [ "$NOHANDSFREE" -o "$VOL" = 0 ]
		then # turn off
			amixer -c "$NUM" -q set "Handsfree Left Playback" "Off" || exit
			amixer -c "$NUM" -q set "Handsfree Right Playback" "Off" || exit
		else
			amixer -c "$NUM" -q set "Handsfree Left Playback" "HF DAC" || exit
			amixer -c "$NUM" -q set "Handsfree Right Playback" "HF DAC" || exit
			amixer -c "$NUM" -q set "Handsfree" "$VOL%" || exit
		fi
		amixer -c "$NUM" -q set "Headset" "$VOL%" || exit
		amixer -c "$NUM" -q set "Earphone" "$VOL%" || exit
		LASTVOL=$VOL
	fi
	sleep 0.1
done
