#!/bin/bash
#
# Pyra volume control daemon
#

GPADC=$(/root/findiio "palmas-gpadc")

[ "$GPADC" ] || exit 1

LASTVOL="unknown"
MAXWHEEL=1200	# reports 0..1250 mV but leave some margin

if [ "$1" = -q ]
then
	QUIET=true
fi

while true
do
	WHEEL=$(cat $GPADC/in_voltage2_input 2>/dev/null)
	# could apply non-linear scale for smoother control
	VOL=$(( 100 * ${WHEEL:-0} / $MAXWHEEL ))
	[ "$VOL" -lt 0 ] && VOL=0
	[ "$VOL" -gt 100 ] && VOL=100
	# should check for abs($VOL-$LASTVOL) > threshold
	if [ "$VOL" != "$LASTVOL" ]
	then # update only if changed since amixer command needs some resources
		[ "$QUIET" ] || echo $WHEEL - $VOL%
		if [ "$VOL" = 0 ]
		then
			amixer -q set "Handsfree Left Playback" "Off" || exit
			amixer -q set "Handsfree Right Playback" "Off" || exit
		else
			amixer -q set "Handsfree Left Playback" "HF DAC" || exit
			amixer -q set "Handsfree Right Playback" "HF DAC" || exit
			amixer -q set "Handsfree" "$VOL%" || exit
			amixer -q set "Headset" "$VOL%" || exit
			amixer -q set "Earphone" "$VOL%" || exit
		fi
		LASTVOL=$VOL
	fi
	sleep 0.1
done