#!/bin/bash
#
# set up wlan connection
#

read -t 5 WLAN OTHER < <(iwconfig 2>&1 | fgrep 'wlan')
[ "$WLAN" ] || WLAN=wlan0

case "$1" in
	-a ) # ad hoc network
		iwconfig $WLAN mode ad-hoc essid Letux enc off channel 6 &&
		ifconfig $WLAN 10.1.1.1
		;;

	'' )
		wpa_supplicant -B -i $WLAN -c /etc/wpa_supplicant/wpa_supplicant.conf
		;;
	-* )
		echo "usage: $0 -a | ssid"
		echo "  -a:     ad hoc mode"
		echo "  ssid:   SSID to connect to"
		;;

	* ) # simple client
		ifconfig $WLAN up &&
		iwconfig $WLAN essid "$1" &&
		dhclient $WLAN
		;;

esac
