#!/bin/sh
#
# turn off UMTS modem
#

SCRIPTPATH="$(dirname "$0")"

if [ -r /dev/ttyACM1 ]
then	# this is a PLS8
	(cd $SCRIPTPATH && make femtocom 2>/dev/null >&2)
	# ignore errors
	(echo AT^SMSO; sleep 1) | $SCRIPTPATH/femtocom /dev/ttyACM1 2>/dev/null || true
	rfkill block wwan
	for i in 1 2 3 4 5 6 7 8 9 10	11 12 13 14 15 # try up to 15 seconds...
	do
		if [ -r /dev/ttyACM1 ]
		then
			:
		else
			break # ...until port has been closed
		fi
		sleep 1
	done
else
	rfkill block wwan
fi

echo modem is off
