#!/bin/bash
#
# capture screen shot as png from X11
#

SCRIPTPATH="$(dirname "$0")"

[ "$(which convert)" ] || apt-get install graphicsmagick-imagemagick-compat || exit 1

. $SCRIPTPATH/x

FILE="$1"
[ "$FILE" ] || FILE=screenshot.png

xwd -root | convert - "$FILE"
